export const adminPolicyCopy = {
	en: {
		title: 'Global policy',
		description: 'Set the server-owned VM gabarit, user quota, and custom cloud-init access.',
		gabarit: 'VM gabarit',
		quota: 'User quota',
		allowCustomYaml: 'Allow custom cloud-init snippets',
		maxSockets: 'Maximum sockets',
		maxCores: 'Maximum cores',
		maxMemory: 'Maximum memory (MB)',
		maxDisk: 'Maximum disk per VM (GB)',
		maxNetworkCards: 'Maximum network cards',
		maxSnapshots: 'Maximum snapshots',
		maxVmPerUser: 'Maximum VMs per user',
		unlimitedHint: '-1 means unlimited',
		save: 'Save policy',
		saving: 'Saving…',
		saved: 'Policy saved',
		loading: 'Loading policy…',
		retry: 'Retry',
		cancel: 'Cancel',
		nodeTitle: 'Node capacity',
		nodeDescription: 'Review live usage and set optional per-node capacity ceilings.',
		node: 'Node',
		actions: 'Actions',
		capacity: 'Capacity',
		usage: 'Usage',
		physical: 'Physical',
		maxVms: 'Maximum VMs',
		maxVcpus: 'Maximum vCPUs',
		maxRam: 'Maximum RAM (GB)',
		maxNodeDisk: 'Maximum disk (GB)',
		edit: 'Edit capacity',
		saveCapacity: 'Save capacity',
		noCap: '0 means no cap'
	},
	fr: {
		title: 'Politique globale',
		description: 'Définissez le gabarit VM, le quota utilisateur et l’accès cloud-init contrôlés par le serveur.',
		gabarit: 'Gabarit VM',
		quota: 'Quota utilisateur',
		allowCustomYaml: 'Autoriser les snippets cloud-init personnalisés',
		maxSockets: 'Nombre maximal de sockets',
		maxCores: 'Nombre maximal de cœurs',
		maxMemory: 'Mémoire maximale (Mo)',
		maxDisk: 'Disque maximal par VM (Go)',
		maxNetworkCards: 'Nombre maximal de cartes réseau',
		maxSnapshots: 'Nombre maximal de snapshots',
		maxVmPerUser: 'Nombre maximal de VM par utilisateur',
		unlimitedHint: '-1 signifie illimité',
		save: 'Enregistrer la politique',
		saving: 'Enregistrement…',
		saved: 'Politique enregistrée',
		loading: 'Chargement de la politique…',
		retry: 'Réessayer',
		cancel: 'Annuler',
		nodeTitle: 'Capacité des nœuds',
		nodeDescription: 'Consultez l’usage courant et définissez les capacités facultatives par nœud.',
		node: 'Nœud',
		actions: 'Actions',
		capacity: 'Capacité',
		usage: 'Usage',
		physical: 'Physique',
		maxVms: 'Nombre maximal de VM',
		maxVcpus: 'Nombre maximal de vCPU',
		maxRam: 'RAM maximale (Go)',
		maxNodeDisk: 'Disque maximal (Go)',
		edit: 'Modifier la capacité',
		saveCapacity: 'Enregistrer la capacité',
		noCap: '0 signifie sans plafond'
	}
} as const;
