---
services:
  pvmss:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pvmss
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "50000:50000"
    environment:
      - PORT=50000
      - TZ=Europe/Paris
    volumes:
      - pvmss_data:/app/data
      # Mount only the settings file and data that might change
      - ./backend/settings.json:/app/settings.json:ro
    networks:
      - pvmss-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:50000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G

networks:
  pvmss-network:
    driver: bridge

volumes:
  pvmss_data:
    driver: local
