---
services:
  pvmss:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pvmss
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "50000:50000/tcp"
    environment:
      PORT: "50000"
      TZ: "Europe/Paris"
    volumes:
      - ./backend/settings.json:/app/settings.json
    # Note: Healthcheck removed due to distroless base image (no wget/curl available)
    # Use external monitoring to check http://localhost:50000/health endpoint
    # The restart policy will handle container failures automatically
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
