apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pvmss.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  {{- with $.Values.extraAnnotations }}
  annotations: {{ include "pvmss.merge" . | toYaml | nindent 4 }}
  {{- end }}
data:
  settings.json: |
{{ .Values.config.settingsJson | indent 4 }}
