{{- if .Values.persistence.db.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pvmss.fullname" . }}-db-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.db.size }}
  {{- if .Values.persistence.db.storageClass }}
  storageClassName: {{ .Values.persistence.db.storageClass }}
  {{- end }}
{{- end }}
