{{- if .Values.persistence.settings.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pvmss.fullname" . }}-settings-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.settings.size }}
  {{- if .Values.persistence.settings.storageClass }}
  storageClassName: {{ .Values.persistence.settings.storageClass }}
  {{- end }}
{{- end }}
