apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pvmss.fullname" . }}-secrets
  namespace: {{ .Values.namespace }}
  {{- with $.Values.extraAnnotations }}
  annotations: {{ include "pvmss.merge" . | toYaml | nindent 4 }}
  {{- end }}
type: Opaque
data:
  admin-password-hash: {{ .Values.secrets.adminPasswordHash | b64enc }}
  pve-api-token: {{ .Values.secrets.pveApiToken | b64enc }}
  session-secret: {{ .Values.secrets.sessionSecret | b64enc }}
