{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  {{- with $.Values.extraAnnotations }}
  annotations: {{ include "pvmss.merge" . | toYaml | nindent 4 }}
  {{- end }}
  {{- with $.Values.extraLabels }}
  labels: {{ include "pvmss.merge" . | toYaml | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountToken }}
{{- end }}
