# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: backend/go.mod
        cache: true

    - name: Verify dependencies
      run: go mod verify
      working-directory: backend

    - name: Build
      run: go build -v ./...
      working-directory: backend

    - name: Test
      run: go test -v ./...
      working-directory: backend
      env:
        PVMSS_OFFLINE: true
        LOG_LEVEL: ERROR
        GO_TEST_ENVIRONMENT: 1
