# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: backend/go.mod
        cache: true

    - name: Verify dependencies
      run: go mod verify
      working-directory: backend

    - name: Build
      run: go build -v ./...
      working-directory: backend

    - name: Test
      run: go test -v ./...
      working-directory: backend
      env:
        ADMIN_PASSWORD_HASH: $2y$10$Ppg7Wl3sNYrmxZmWgcq4reOyznt7AeqMrQucaH4HY.dBrzavhPP1e
        GO_TEST_ENVIRONMENT: 1
        LOG_LEVEL: INFO
        PROXMOX_API_TOKEN_NAME: tokenName@changeMe!value
        PROXMOX_API_TOKEN_VALUE: aaaaaaaaaa-0000-44aa-1111-aaaaaaaaaaa
        PROXMOX_URL: https://localhost:8006/api2/json
        PROXMOX_VERIFY_SSL: false
        PVMSS_OFFLINE: true
        SESSION_SECRET: changeMeWithSomethingElseUnique
